name: flask
description: A starter component that uses Flask framework and SQLite database.

keywords:
  - Flask
  - SQLite
  - Python
  - HTML
  - Gunicorn

secrets:
  flask_env:
    description: Environment in which Flask application runs
    default: production
  gunicorn_workers:
    description: Number of Gunicorn worker processes
    default: 4

services:
  app:
    build:
      context: ./
    interfaces:
      main: &app-port 5000
    environment:
      FLASK_ENV: ${{ secrets.flask_env }}
      FLASK_PORT: *app-port
      FLASK_APP: ./app.py
    # liveness_probe:
    #   command: curl --fail 0.0.0.0:5000
    #   interval: 30s
    #   failure_threshold: 3
    command:
      - sh
      - -c
      - |
        gunicorn -w ${{ secrets.gunicorn_workers }} -b 0.0.0.0:${{ services.app.interfaces.main.port }} "flaskr:create_app()"
    debug:
      environment:
        FLASK_ENV: development
        FLASK_DEBUG: 1
      command: flask run --host=0.0.0.0
      volumes:
        src:
          host_path: ./flaskr/
          mount_path: /app/flaskr

interfaces:
  app:
    url: ${{ services.app.interfaces.main.url }}
    ingress:
      subdomain: app
